### ISSUE TITLE
Run on Cubietruck fails

### ISSUE THREAD

**Issue by werwolfby** [NARKOZ/ginatra#39]
I've installed ginatra on my [cubietruck](http://www.cubietruck.com/) running under cubian:
```
Linux cubietruck 3.4.79-sun7i #19 SMP PREEMPT Fri Oct 10 03:20:03 CST 2014 armv7l GNU/Linux
```

gem install was successful.
But when I try to run ginatra by *ginatra run* I have next output:
```
ginatra run
/var/lib/gems/1.9.1/gems/ginatra-4.0.2/config.ru:17:in `block in <main>': uninitialized constant MakeMakefile (NameError)
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
        from /var/lib/gems/1.9.1/gems/ginatra-4.0.2/config.ru:in `new'
        from /var/lib/gems/1.9.1/gems/ginatra-4.0.2/config.ru:in `<main>'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/server.rb:272:in `start'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/server.rb:147:in `start'
        from /var/lib/gems/1.9.1/gems/rack-1.6.0/bin/rackup:4:in `<top (required)>'
        from /usr/local/bin/rackup:23:in `load'
        from /usr/local/bin/rackup:23:in `<main>'
Ginatra runs on localhost:9797
```

config.yml:
```yaml
# Default config file for Ginatra
# Settings specified in '~/.ginatra/config.yml' will take precedence over these
git_dirs:
  - /mnt/media/Repositories/*
sitename: Ginatra
description: "My Git Repositories"
port: 9797
host: localhost
prefix: "/"
git_clone_enabled?: true
```
